### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by Random3131** [MrsRina/onepop#14]
// I let you down. Sorry :(

Time: 5/6/22 9:56 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.network.EnumConnectionState.func_150752_a(SourceFile:349)
	at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:209)
	at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:168)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147297_a(NetHandlerPlayClient.java:805)
	at rina.onepop.club.api.tracker.management.TrackerManager.onUpdateAll(TrackerManager.java:48)
	at rina.onepop.club.api.event.management.EventManager.onTick(EventManager.java:88)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_EventManager_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.network.EnumConnectionState.func_150752_a(SourceFile:349)
	at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:209)
	at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:168)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147297_a(NetHandlerPlayClient.java:805)
	at rina.onepop.club.api.tracker.management.TrackerManager.onUpdateAll(TrackerManager.java:48)
	at rina.onepop.club.api.event.management.EventManager.onTick(EventManager.java:88)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_EventManager_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 4 total; [EntityPlayerSP['Novasweetz'/8204, l='MpServer', x=81.91, y=3.00, z=181.30], EntityOtherPlayerMP['Feelin'/4460, l='MpServer', x=88.49, y=4.00, z=192.65], EntityOtherPlayerMP['Morisa_'/6967, l='MpServer', x=81.39, y=2.00, z=178.66], EntityOtherPlayerMP['NovaEnthusiast'/8153, l='MpServer', x=49.56, y=152.00, z=166.00]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (69,152,164), Chunk: (at 5,9,4 in 4,10; contains blocks 64,0,160 to 79,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 25491 game time, 1304236565 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntityPlayerSP['Novasweetz'/8204, l='MpServer', x=81.91, y=3.00, z=181.30], EntityOtherPlayerMP['DisguisedTortise'/5098, l='MpServer', x=102.99, y=4.12, z=130.92], EntityOtherPlayerMP['Feelin'/4460, l='MpServer', x=88.49, y=4.00, z=192.65], EntityOtherPlayerMP['GS_StarGamer'/1778, l='MpServer', x=100.59, y=3.80, z=133.74], EntityOtherPlayerMP['Morisa_'/6967, l='MpServer', x=81.39, y=2.00, z=178.66], EntityOtherPlayerMP['NovaEnthusiast'/8153, l='MpServer', x=49.56, y=152.00, z=166.00], EntityOtherPlayerMP['Reformed08'/7481, l='MpServer', x=103.16, y=4.99, z=134.18], EntityEnderCrystal['entity.EnderCrystal.name'/283, l='MpServer', x=44.50, y=216.00, z=202.50], EntityXPOrb['Experience Orb'/8611, l='MpServer', x=102.75, y=3.00, z=165.92], EntityEnderCrystal['entity.EnderCrystal.name'/2985, l='MpServer', x=46.50, y=3.00, z=153.50], EntityItemFrame['entity.ItemFrame.name'/299, l='MpServer', x=63.50, y=228.50, z=197.97], EntityOtherPlayerMP['Morisa_'/6967, l='MpServer', x=81.39, y=2.00, z=178.66], EntityEnderCrystal['entity.EnderCrystal.name'/7224, l='MpServer', x=57.50, y=5.00, z=156.50], EntityEnderCrystal['entity.EnderCrystal.name'/7225, l='MpServer', x=58.50, y=4.00, z=153.50], EntityEnderCrystal['entity.EnderCrystal.name'/7226, l='MpServer', x=59.50, y=5.00, z=156.50], EntityEnderCrystal['entity.EnderCrystal.name'/7227, l='MpServer', x=56.50, y=5.00, z=158.50], EntityEnderCrystal['entity.EnderCrystal.name'/7228, l='MpServer', x=59.50, y=5.00, z=159.50], EntityEnderCrystal['entity.EnderCrystal.name'/7229, l='MpServer', x=61.50, y=4.00, z=158.50], EntityEnderCrystal['entity.EnderCrystal.name'/8893, l='MpServer', x=105.50, y=4.00, z=149.50], EntityEnderCrystal['entity.EnderCrystal.name'/7230, l='MpServer', x=57.50, y=3.00, z=155.50], EntityEnderCrystal['entity.EnderCrystal.name'/7231, l='MpServer', x=59.50, y=2.00, z=155.50], EntityEnderCrystal['entity.EnderCrystal.name'/7232, l='MpServer', x=60.50, y=5.00, z=154.50], EntityOtherPlayerMP['NovaEnthusiast'/8153, l='MpServer', x=49.56, y=152.00, z=166.00], EntityOtherPlayerMP['Feelin'/4460, l='MpServer', x=88.49, y=4.00, z=192.65], EntityEnderCrystal['entity.EnderCrystal.name'/6772, l='MpServer', x=63.50, y=5.00, z=188.50]]
	Retry entities: 0 total; []
	Server brand: Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by mrsrina** [comment]
I am finding why it crashing, in soon I will commit a fix and release a patch version. Just an additional, the module name is Auto-Refill (I use a queue list for handle some packets into game inventory to prevent ghost slots).

**Comment by Random3131** [comment]
okk thanks
